# Generated by Django 4.1.2 on 2022-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploORM', '0002_persona_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='contrasenna',
            field=models.CharField(max_length=15),
        ),
    ]
