# Generated by Django 4.1.2 on 2022-11-18 15:05

import EjemploORM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploORM', '0003_alter_persona_contrasenna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=EjemploORM.models.marketplace_directory_path)),
                ('slug', models.SlugField(unique=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='productosComprados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EjemploORM.productos')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='EjemploORM.persona')),
            ],
        ),
    ]
