# Generated by Django 4.1.2 on 2022-11-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploORM', '0004_productos_productoscomprados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
