"""
Django settings for EjemploORM project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(zv8#e%@aya&o0)f6*s%qkfn7!!y!3hiz^w_kalci-%bm=i_6b'

# SECURITY WARNING: don't run with debug turned on in production!

#---------------------------------------------------------------------------------------------------

#---------------------------------------------------------------------------------------------------

#---------------------------------------------------------------------------------------------------
#IMPORTANTE!!!
#---------------------------------------------------------------------------------------------------
# USO SOLO PARA RAILWAY
DEBUG = False
#USO LOCAL
DEBUG = True
#---------------------------------------------------------------------------------------------------
#IMPORTANTE
#---------------------------------------------------------------------------------------------------
#  DESCOMENTAR PARA RAILWAY
ALLOWED_HOSTS = ['ecommercevf-production.up.railway.app']

# USO SOLO LOCAL
# ALLOWED_HOSTS = []
#---------------------------------------------------------------------------------------------------



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EjemploORM',
    'crispy_forms',
    'crispy_bootstrap5',
    
]
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EjemploORM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["./EjemploORM/repositorios"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EjemploORM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


#---------------------------------------------------------------------------------------------------
# USO LOCAL, COMENTAR CUANDO USEN EL DE AZURE
#---------------------------------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#---------------------------------------------------------------------------------------------------
#*************************BD AZURE ********************************************
#---------------------------------------------------------------------------------------------------
# IMPORTANTE!!! DESCOMENTAR PARA MYSQL EN AZURE
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ECOMMERCEBD',
#         'USER': 'recismart',
#         'PASSWORD': 'sqlserver.2022',
#         'HOST': 'mysqlrecismart.mysql.database.azure.com',
#         'PORT': '3306',
#     }
# }
#---------------------------------------------------------------------------------------------------



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago'

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATICFILES_DIRS = ["./EjemploORM/static"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#---------------------------------------------------------------------------------------------------
#RAILWAY
#---------------------------------------------------------------------------------------------------
# IMPORTANTE!!!! DESCOMENTAR PARA RAILWAY

CSRF_TRUSTED_ORIGINS = ['https://ecommercevf-production.up.railway.app',
                       'https://www.tejerypunto.cl',
                       'https://tejerypunto.cl']
#---------------------------------------------------------------------------------------------------
